OrderSystem/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from .settings import MEDIA_ROOT
from app03 import views as v3

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('store/',include("app01.urls")),
    path('user/', include("app02.urls")),
    path('rider/', include("app04.urls")),
    path('', v3.login),
    path('login/',v3.login),

]

app01/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app03 import views as v3
urlpatterns = [
    path('index/', views.index),
    path('goodsmanage/',views.goodsmanage),
    path('addgood/',views.addgood),
    path('goodtypemanage/', views.goodtypemanage),
    path('addgoodtype/',views.addgoodtype),
    path('delgoodtype/',views.delgoodtype),
    path('updategood/<int:good_id>',views.updategood),
    path('delgood/<int:good_id>', views.delgood),
    path('searchgood/', views.searchgood),
    path('update_good_num/',views.update_good_num),
    path('orderhall/',views.orderhall),
    path('update_order_status/',views.update_order_status),
    path('ordermanage/',views.ordermanage),
    path('orderdetail/<int:order_id>',views.orderdetail),
    path('searchorder/',views.searchorder),
    path('earnmanage/',views.earnmanage),
    path('echart/',views.echart),
    path('updatepwd/',views.updatepwd),
    path('updateinfo/',views.updateinfo),
    path('login/', views.login),
    path('logout/', views.logout),
    path('register/',v3.storeregister),
]

app01/models.py
from django.db import models


# Create your models here.

class Users(models.Model):
    """
    用户
    """
    user_id = models.AutoField(primary_key=True, verbose_name="用户ID")
    account = models.CharField(max_length=20, verbose_name="账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    user_name = models.CharField(max_length=10, verbose_name="用户名")
    user_tel = models.CharField(max_length=11, verbose_name="手机号")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    user_avatar = models.ImageField(upload_to='user_avatar/', verbose_name="用户头像", default="userDefault.png")
    user_status = models.IntegerField(default=1, verbose_name="用户状态")  # 默认为1,(1,激活)(0,注销)

    class Meta:
        unique_together = ("account", "user_tel")


class Riders(models.Model):
    """
    骑手
    """
    rider_id = models.AutoField(primary_key=True, verbose_name="骑手ID")
    account = models.CharField(max_length=20, verbose_name="骑手账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    rider_name = models.CharField(max_length=5, verbose_name="骑手真实姓名")
    identity_card = models.CharField(max_length=18, verbose_name="身份证")
    identity_card_front = models.ImageField(upload_to='riders_identity_card/', verbose_name="骑手身份证正面")
    identity_card_back = models.ImageField(upload_to='riders_identity_card/', verbose_name="骑手身份证反面")
    rider_tel = models.CharField(max_length=11, verbose_name="手机号")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    rider_status = models.IntegerField(default=1, verbose_name="骑手状态")  # 默认为1,(0,骑手已离职或未激活)(1,骑手休息不接单)(2,骑手上班开始接单)
    earnmoney = models.FloatField(verbose_name="收益", default=0.00)

    class Meta:
        unique_together = ("account", "rider_tel")


class Stores(models.Model):
    """商家"""
    store_id = models.AutoField(primary_key=True, verbose_name="商家ID")
    account = models.CharField(max_length=20, verbose_name="商家账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    real_name = models.CharField(max_length=5, verbose_name="商家真实姓名")
    identity_card = models.CharField(max_length=18, verbose_name="身份证",null=True)
    identity_card_front = models.ImageField(upload_to='stores_identity_card/', verbose_name="商家身份证正面",null=True)
    identity_card_back = models.ImageField(upload_to='stores_identity_card/', verbose_name="商家身份证反面",null=True)
    store_name = models.CharField(max_length=20, verbose_name="商家名称")
    store_avatar = models.ImageField(upload_to='store_avatar/', verbose_name="商家头像", default="storeDefault.png")
    store_tel = models.CharField(max_length=11, verbose_name="手机号")
    address = models.CharField(max_length=20, verbose_name="商家地址")
    open_time = models.TimeField(verbose_name="开店时间")
    close_time = models.TimeField(verbose_name="关店时间")
    remark = models.CharField(max_length=200, null=True, verbose_name="商家介绍")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    store_status = models.IntegerField(default=0, verbose_name="商家状态")  # 默认为0，(0,未认证成功),(1,开始营业)(2,未营业)

    class Meta:
        unique_together = ("account", "store_tel")


class Goods(models.Model):
    """商家商品"""
    good_id = models.AutoField(primary_key=True, verbose_name="商品ID")
    good_name=models.CharField(max_length=15,verbose_name="商品名称")
    good_store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商家")
    good_type = models.ForeignKey("GoodType", null=True, on_delete=models.CASCADE, verbose_name="商品类型")
    good_pic = models.ImageField(upload_to='good_pic/%Y/%m', verbose_name="商品图片", default="good_pic/default.png")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="商品单价", )
    discount = models.FloatField(default=1.00, verbose_name="折扣",null=True,blank=True)
    good_num = models.IntegerField(default=0, verbose_name="商品库存")
    remark = models.CharField(max_length=200, null=True, verbose_name="商品介绍")
    good_status=models.IntegerField(default=1, verbose_name="商品状态")  # 默认为1(0,已删除)(1,激活)(2,下架)


class GoodType(models.Model):
    goodtype_id = models.AutoField(primary_key=True, verbose_name="商品类型ID")
    goodtype_name = models.CharField(max_length=10, verbose_name="商品类型名称")
    store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商店id")
    goodtype_status = models.IntegerField(default=1, verbose_name="商品类型状态")  # 默认为1(0,已删除)(1,激活)


class Orders(models.Model):
    """订单"""
    order_id = models.AutoField(primary_key=True, verbose_name="订单ID")
    order_user = models.ForeignKey("Users", on_delete=models.CASCADE, verbose_name="用户id")
    order_rider = models.ForeignKey("Riders", on_delete=models.CASCADE, verbose_name="骑手id",null=True)
    order_store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商家id")
    order_address = models.ForeignKey("Address", on_delete=models.CASCADE, verbose_name="送餐地址id")
    total_price = models.FloatField(verbose_name="总价")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="订单创建时间")
    finish_time = models.DateTimeField(verbose_name="完成时间", null=True)
    order_status = models.IntegerField(default=1, verbose_name="订单状态")
    # 默认为1,(0,订单删除or取消)(1,商家未接单)(2,商家已接单)(3,骑手已接单)(4,骑手取到商品)(5,骑手已送达)
    order_detail = models.ManyToManyField("Goods", through="Order_details")
    comment = models.OneToOneField("Comment", null=True, on_delete=models.CASCADE, verbose_name="评论id")

class Order_details(models.Model):
    """订单详情"""
    order_detail_id = models.AutoField(primary_key=True, verbose_name="订单详情ID")
    order = models.ForeignKey("Orders", on_delete=models.CASCADE, verbose_name="订单")
    good = models.ForeignKey("Goods", on_delete=models.CASCADE, verbose_name="商品id")
    number = models.IntegerField(default=1, verbose_name="数量")
    discount_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="折扣后单价")


class Address(models.Model):
    """用户地址"""
    address_id = models.AutoField(primary_key=True, verbose_name="地址id")
    location = models.CharField(max_length=20, verbose_name="地址")
    address_user = models.ForeignKey("Users", on_delete=models.CASCADE, verbose_name="用户")
    address_name = models.CharField(max_length=10, verbose_name="姓名")
    address_tel = models.CharField(max_length=11, verbose_name="手机号")
    sex = models.IntegerField(default=1, verbose_name="性别")  # 默认为1,(1,男)(2,女)
    address_status = models.IntegerField(default=1, verbose_name="地址状态")  # 默认未1(0,删除)(1,未删除)


class Comment(models.Model):
    """用户评价"""
    comment_id = models.AutoField(primary_key=True, verbose_name="评价ID")
    comment_content = models.CharField(max_length=300, verbose_name="评价内容")
    level=models.IntegerField(default=1,verbose_name="星级评分")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    comment_status = models.IntegerField(default=1, verbose_name="评论状态")  # 默认为1,(0,已删除)(1,已评论)(2,商家已读)

app02/forms.py
from django.forms import Form
from django import forms
from  django.forms import fields
class UpdateForm(Form):
    user_id = fields.IntegerField()
    account = fields.CharField(
        max_length=20,
        required=True,
        error_messages={
            'required':'用户名不能为空',
            'max_length':'太长了',
        }
    )
    pwd = fields.CharField(
        max_length=16,
        required=True,
        error_messages={
            'required': '用户名不能为空',
            'max_length': '太长了',
        }
    )
    user_name = fields.CharField(
        max_length=10,
        required=True,
        error_messages={
            'required': '用户名不能为空',
            'max_length': '太长了',
        }
    )
    user_tel = fields.CharField(
        max_length=11,
        required=True,
        error_messages={
            'required': '用户名不能为空',
            'max_length': '太长了',
        }
    )

class UserOrder(forms.Form):
    total_price = forms.FloatField(error_messages={'required':'用户名为空'})
    store_id = forms.IntegerField(error_messages={'required':'用户名为空'})


class AddressAdd(forms.Form):
    location = forms.CharField(max_length=20,error_messages={'required':'用户名为空'})
    user_name = forms.CharField(max_length=10,error_messages={'required':'用户名为空'})
    address_tel = forms.CharField(max_length=11,error_messages={'required':'用户名为空'})
    sex =forms.IntegerField(error_messages={'required':'用户名为空'})
class EditAddress(forms.Form):
    address_id = forms.IntegerField()
    location = forms.CharField(max_length=20,error_messages={'required':'用户名为空'})
    user_name = forms.CharField(max_length=10,error_messages={'required':'用户名为空'})
    address_tel = forms.CharField(max_length=11,error_messages={'required':'用户名为空'})
    sex =forms.IntegerField(error_messages={'required':'用户名为空'})

templates/Base/RiderRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商家注册</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<div style="width: 1000px;margin: 0 auto">
    <h1 align="center">骑手注册</h1>
    <form action="/rider/register/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_account">账号</label>
            {{ form.account }}
        </div>
        <div class="form-group">
            <label for="id_pwd">密码</label>
            {{ form.pwd }}
        </div>
        <div class="form-group">
            <label for="id_check_pwd">确认密码:</label>
            {{ form.check_pwd }}
        </div>

        <div class="form-group">
            <label for="id_rider_name">真实姓名</label>
            {{ form.rider_name }}
        </div>
            <div class="form-group">
            <label for="id_identity_card">身份证号:</label>
            {{ form.identity_card }}
        </div>
        <div class="form-group">
            <label for="id_user_tel">联系电话</label>
            {{ form.rider_tel }}
        </div>
        <button type="submit" class="btn btn-default">注册</button>
    </form>
</div>
</body>
</html>

templates/Base/StoreRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商家注册</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<div style="width: 1000px;margin: 0 auto">
    <h1 align="center">商家注册</h1>
    <form action="/store/register/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_account">账号</label>
            {{ form.account }}
        </div>
        <div class="form-group">
            <label for="id_pwd">密码</label>
            {{ form.pwd }}
        </div>
        <div class="form-group">
            <label for="id_check_pwd">确认密码:</label>
            {{ form.check_pwd }}
        </div>
        <div class="form-group">
            <label for="id_real_name">真实姓名</label>
            {{ form.real_name }}
        </div>
        <div class="form-group">
            <label for="id_identity_card">身份证号:</label>
            {{ form.identity_card }}
        </div>
        <div class="form-group">
            <label for="id_store_name">店名</label>
            {{ form.store_name }}
        </div>
        <div class="form-group">
            <label for="id_store_avatar">商家头像</label>
            {{ form.store_avatar }}
        </div>
        <div class="form-group">
            <label for="id_store_tel">联系电话</label>
            {{ form.store_tel }}
        </div>
        <div class="form-group">
            <label for="id_store_address">联系地址</label>
            {{ form.address }}
        </div>
        <div class="form-group">
            <label for="id_open_time">开店时间</label>
            {{ form.open_time }}
        </div>
        <div class="form-group">
            <label for="id_close_time">关店时间</label>
            {{ form.close_time }}
        </div>
        <div class="form-group">
            <label for="id_close_time">商家介绍</label>
            {{ form.remark }}
        </div>
        <button type="submit" class="btn btn-default">注册</button>
    </form>
</div>
</body>
</html>

templates/Base/UserRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商家注册</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<div style="width: 1000px;margin: 0 auto">
    <h1 align="center">用户注册</h1>
    <form action="/user/register/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_account">账号</label>
            {{ form.account }}
        </div>
        <div class="form-group">
            <label for="id_pwd">密码</label>
            {{ form.pwd }}
        </div>
        <div class="form-group">
            <label for="id_check_pwd">确认密码:</label>
            {{ form.check_pwd }}
        </div>

        <div class="form-group">
            <label for="id_user_name">昵称</label>
            {{ form.user_name }}
        </div>
        <div class="form-group">
            <label for="id_user_avatar">头像</label>
            {{ form.user_avatar }}
        </div>
        <div class="form-group">
            <label for="id_user_tel">联系电话</label>
            {{ form.user_tel }}
        </div>
        <button type="submit" class="btn btn-default">注册</button>
    </form>
</div>
</body>
</html>

templates/Base/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="/static/plugins/layui/css/layui.css">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <style>
        .layui-tab-title{
            border-bottom-width: 1px;
        }
        .layui-tab-title .layui-this:after{
            border-bottom-color:#fff
        }
    </style>
</head>
<body>
<div class="layui-tab" style="width: 500px;margin: 0 auto;border: 1px solid #e6e6e6;margin-top: 200px">
  <ul class="layui-tab-title" style="box-sizing: unset;">
    <li class="layui-this">用户</li>
    <li>商家</li>
    <li>骑手</li>

  </ul>
  <div class="layui-tab-content">
    <div class="layui-tab-item layui-show">
        <form action="/login/" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="1">
            <div class="form-group">
            <label for="account">用户名</label>
            <input type="text" class="form-control" id="account"  name="account">
          </div>
          <div class="form-group">
            <label for="pwd">密码</label>
            <input type="password" class="form-control" id="pwd" name="pwd">
          </div>
        <button type="submit" class="btn btn-primary">登录</button>
            <a href="/user/register/" class="btn btn-default">注册</a>
        </form>
    </div>
    <div class="layui-tab-item">
        <form action="/login/" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="2">
            <div class="form-group">
            <label for="account">用户名</label>
            <input type="text" class="form-control" id="account" name="account">
          </div>
          <div class="form-group">
            <label for="pwd">密码</label>
            <input type="password" class="form-control" id="pwd" name="pwd">
          </div>
        <button type="submit" class="btn btn-primary">登录</button>
        <a href="/store/register/" class="btn btn-default">注册</a>
        </form>
    </div>
    <div class="layui-tab-item">
        <form action="/login/" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="3">
            <div class="form-group">
            <label for="account">用户名</label>
            <input type="text" class="form-control" id="account" name="account">
          </div>
          <div class="form-group">
            <label for="pwd">密码</label>
            <input type="password" class="form-control" id="pwd" name="pwd">
          </div>
        <button type="submit" class="btn btn-primary">登录</button>
        <a href="/rider/register/" class="btn btn-default">注册</a>
        </form>
    </div>
  </div>
</div>

<script src="/static/plugins/layui/layui.js"></script>
<script>
layui.use('element', function(){
  var $ = layui.jquery
  ,element = layui.element; //Tab的切换功能，切换事件监听等，需要依赖element模块

  //触发事件
  var active = {
    tabAdd: function(){
      //新增一个Tab项
      element.tabAdd('demo', {
        title: '新选项'+ (Math.random()*1000|0) //用于演示
        ,content: '内容'+ (Math.random()*1000|0)
        ,id: new Date().getTime() //实际使用一般是规定好的id，这里以时间戳模拟下
      })
    }
  };

  $('.site-demo-active').on('click', function(){
    var othis = $(this), type = othis.data('type');
    active[type] ? active[type].call(this, othis) : '';
  });


});
</script>
</body>
</html>