OrderSystem/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from .settings import MEDIA_ROOT
from app03 import views as v3

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('store/',include("app01.urls")),
    path('user/', include("app02.urls")),
    path('rider/', include("app04.urls")),
    path('', v3.login),
    path('login/',v3.login),

]

app01/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app03 import views as v3
urlpatterns = [
    path('index/', views.index),
    path('goodsmanage/',views.goodsmanage),
    path('addgood/',views.addgood),
    path('goodtypemanage/', views.goodtypemanage),
    path('addgoodtype/',views.addgoodtype),
    path('delgoodtype/',views.delgoodtype),
    path('updategood/<int:good_id>',views.updategood),
    path('delgood/<int:good_id>', views.delgood),
    path('searchgood/', views.searchgood),
    path('update_good_num/',views.update_good_num),
    path('orderhall/',views.orderhall),
    path('update_order_status/',views.update_order_status),
    path('ordermanage/',views.ordermanage),
    path('orderdetail/<int:order_id>',views.orderdetail),
    path('searchorder/',views.searchorder),
    path('earnmanage/',views.earnmanage),
    path('echart/',views.echart),
    path('updatepwd/',views.updatepwd),
    path('updateinfo/',views.updateinfo),
    path('login/', views.login),
    path('logout/', views.logout),
    path('register/',v3.storeregister),
]

app01/models.py
from django.db import models


# Create your models here.

class Users(models.Model):
    """
    用户
    """
    user_id = models.AutoField(primary_key=True, verbose_name="用户ID")
    account = models.CharField(max_length=20, verbose_name="账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    user_name = models.CharField(max_length=10, verbose_name="用户名")
    user_tel = models.CharField(max_length=11, verbose_name="手机号")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    user_avatar = models.ImageField(upload_to='user_avatar/', verbose_name="用户头像", default="userDefault.png")
    user_status = models.IntegerField(default=1, verbose_name="用户状态")  # 默认为1,(1,激活)(0,注销)

    class Meta:
        unique_together = ("account", "user_tel")


class Riders(models.Model):
    """
    骑手
    """
    rider_id = models.AutoField(primary_key=True, verbose_name="骑手ID")
    account = models.CharField(max_length=20, verbose_name="骑手账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    rider_name = models.CharField(max_length=5, verbose_name="骑手真实姓名")
    identity_card = models.CharField(max_length=18, verbose_name="身份证")
    identity_card_front = models.ImageField(upload_to='riders_identity_card/', verbose_name="骑手身份证正面")
    identity_card_back = models.ImageField(upload_to='riders_identity_card/', verbose_name="骑手身份证反面")
    rider_tel = models.CharField(max_length=11, verbose_name="手机号")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    rider_status = models.IntegerField(default=1, verbose_name="骑手状态")  # 默认为1,(0,骑手已离职或未激活)(1,骑手休息不接单)(2,骑手上班开始接单)
    earnmoney = models.FloatField(verbose_name="收益", default=0.00)

    class Meta:
        unique_together = ("account", "rider_tel")


class Stores(models.Model):
    """商家"""
    store_id = models.AutoField(primary_key=True, verbose_name="商家ID")
    account = models.CharField(max_length=20, verbose_name="商家账号")
    pwd = models.CharField(max_length=16, verbose_name="密码")
    real_name = models.CharField(max_length=5, verbose_name="商家真实姓名")
    identity_card = models.CharField(max_length=18, verbose_name="身份证",null=True)
    identity_card_front = models.ImageField(upload_to='stores_identity_card/', verbose_name="商家身份证正面",null=True)
    identity_card_back = models.ImageField(upload_to='stores_identity_card/', verbose_name="商家身份证反面",null=True)
    store_name = models.CharField(max_length=20, verbose_name="商家名称")
    store_avatar = models.ImageField(upload_to='store_avatar/', verbose_name="商家头像", default="storeDefault.png")
    store_tel = models.CharField(max_length=11, verbose_name="手机号")
    address = models.CharField(max_length=20, verbose_name="商家地址")
    open_time = models.TimeField(verbose_name="开店时间")
    close_time = models.TimeField(verbose_name="关店时间")
    remark = models.CharField(max_length=200, null=True, verbose_name="商家介绍")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间")
    store_status = models.IntegerField(default=0, verbose_name="商家状态")  # 默认为0，(0,未认证成功),(1,开始营业)(2,未营业)

    class Meta:
        unique_together = ("account", "store_tel")


class Goods(models.Model):
    """商家商品"""
    good_id = models.AutoField(primary_key=True, verbose_name="商品ID")
    good_name=models.CharField(max_length=15,verbose_name="商品名称")
    good_store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商家")
    good_type = models.ForeignKey("GoodType", null=True, on_delete=models.CASCADE, verbose_name="商品类型")
    good_pic = models.ImageField(upload_to='good_pic/%Y/%m', verbose_name="商品图片", default="good_pic/default.png")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="商品单价", )
    discount = models.FloatField(default=1.00, verbose_name="折扣",null=True,blank=True)
    good_num = models.IntegerField(default=0, verbose_name="商品库存")
    remark = models.CharField(max_length=200, null=True, verbose_name="商品介绍")
    good_status=models.IntegerField(default=1, verbose_name="商品状态")  # 默认为1(0,已删除)(1,激活)(2,下架)


class GoodType(models.Model):
    goodtype_id = models.AutoField(primary_key=True, verbose_name="商品类型ID")
    goodtype_name = models.CharField(max_length=10, verbose_name="商品类型名称")
    store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商店id")
    goodtype_status = models.IntegerField(default=1, verbose_name="商品类型状态")  # 默认为1(0,已删除)(1,激活)


class Orders(models.Model):
    """订单"""
    order_id = models.AutoField(primary_key=True, verbose_name="订单ID")
    order_user = models.ForeignKey("Users", on_delete=models.CASCADE, verbose_name="用户id")
    order_rider = models.ForeignKey("Riders", on_delete=models.CASCADE, verbose_name="骑手id",null=True)
    order_store = models.ForeignKey("Stores", on_delete=models.CASCADE, verbose_name="商家id")
    order_address = models.ForeignKey("Address", on_delete=models.CASCADE, verbose_name="送餐地址id")
    total_price = models.FloatField(verbose_name="总价")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="订单创建时间")
    finish_time = models.DateTimeField(verbose_name="完成时间", null=True)
    order_status = models.IntegerField(default=1, verbose_name="订单状态")
    # 默认为1,(0,订单删除or取消)(1,商家未接单)(2,商家已接单)(3,骑手已接单)(4,骑手取到商品)(5,骑手已送达)
    order_detail = models.ManyToManyField("Goods", through="Order_details")
    comment = models.OneToOneField("Comment", null=True, on_delete=models.CASCADE, verbose_name="评论id")

class Order_details(models.Model):
    """订单详情"""
    order_detail_id = models.AutoField(primary_key=True, verbose_name="订单详情ID")
    order = models.ForeignKey("Orders", on_delete=models.CASCADE, verbose_name="订单")
    good = models.ForeignKey("Goods", on_delete=models.CASCADE, verbose_name="商品id")
    number = models.IntegerField(default=1, verbose_name="数量")
    discount_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="折扣后单价")


class Address(models.Model):
    """用户地址"""
    address_id = models.AutoField(primary_key=True, verbose_name="地址id")
    location = models.CharField(max_length=20, verbose_name="地址")
    address_user = models.ForeignKey("Users", on_delete=models.CASCADE, verbose_name="用户")
    address_name = models.CharField(max_length=10, verbose_name="姓名")
    address_tel = models.CharField(max_length=11, verbose_name="手机号")
    sex = models.IntegerField(default=1, verbose_name="性别")  # 默认为1,(1,男)(2,女)
    address_status = models.IntegerField(default=1, verbose_name="地址状态")  # 默认未1(0,删除)(1,未删除)


class Comment(models.Model):
    """用户评价"""
    comment_id = models.AutoField(primary_key=True, verbose_name="评价ID")
    comment_content = models.CharField(max_length=300, verbose_name="评价内容")
    level=models.IntegerField(default=1,verbose_name="星级评分")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    comment_status = models.IntegerField(default=1, verbose_name="评论状态")  # 默认为1,(0,已删除)(1,已评论)(2,商家已读)

templates/Store/EarnManage.html
{% extends 'Store/storebase.html' %}
{% block title %}
    收益
{% endblock %}
{% block css %}
<style>

</style>
{% endblock %}
{% block leftside %}
    {% include 'Store/storeleftside.html' %}
{% endblock %}

{% block main %}
    <div class="main">
                            <a data-toggle="modal" href="/store/orderdetail/1"
                               data-target="#show_details">查看详情</a>
        <div class="row" style="width: 1500px;margin: 0 auto;margin-top: 15px;">
            <div class="col-md-4" >
                <div class="panel panel-default" >
                    <div class="panel-heading">
                        <h3 class="panel-title">今日销售总额</h3>
                    </div>
                    <div class="panel-body">
                        今日成交：{{ today.num }}单<br>订单总额： <i class="fa fa-jpy" aria-hidden="true"> {% if today.price %}{{ today.price }}{% else %}&nbsp;0{% endif %}</i>
                    </div>
                </div>

            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">昨日销售总额</h3>
                    </div>
                    <div class="panel-body">
                        作日日成交：{{ yesterday.num }}单<br>订单总额：<i class="fa fa-jpy"
                                                              aria-hidden="true">{% if yesterday.price %}{{ yesterday.price }}{% else %}&nbsp;0{% endif %} </i>
                    </div>
                </div>

            </div>
            <div class="col-md-4" >
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">本月销售总额</h3>
                    </div>
                    <div class="panel-body">
                        本月成交：{{ curmonth.num }}单 <br>订单总额： <i class="fa fa-jpy"
                                                              aria-hidden="true"> {% if curmonth %}{{ curmonth.price }}{% else %}&nbsp;0{% endif %}</i>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><h3 style="float: left;line-height: 5px">订单统计</h3>
                                        <input type="text" style="width: 200px;" class="layui-input" id="sell_time" placeholder="查看月销售统计">
</div>
            </div>
            <div class="panel-body">
                {{ barchart |safe }}
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade bs-example-modal-lg " id="show_details" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="/static/plugins/layui/layui.js"></script>
    <script>
        $("#leftside li:eq(3)").addClass("layui-this")
        layui.use('laydate', function(){
          var laydate = layui.laydate;
            laydate.render({
            elem: '#sell_time'
            ,type: 'month'
          });
        })
    $("#sell_time").blur(function () {
        var searchtime=$(this).val()
        console.log(searchtime)
        if(searchtime){
            $("#show_details").modal({
            remote: '/store/echart/?searchtime='+searchtime    // 从远程加载内容的地址
        });
        }
    })
        $('#show_details').on('hidden.bs.modal', function () {
            $(this).removeData("bs.modal");
            $(this).find(".modal-content").children().remove();
        })
    </script>
{% endblock %}

templates/Store/OrderDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel" align="center">订单编号：{{ order.order_id }}</h4>
    </div>
    <div class="modal-body">
        <div style="min-height: 300px">
            {% for detail in detail_list %}
                <dl class="dl-horizontal">
                    <dt>{{ detail.good__good_name }}</dt>
                    <dd>x{{ detail.number }}</dd>
                </dl>

            {% endfor %}
        </div>
        <hr>
        <p style="float: right" align="right"><i class="fa fa-jpy"
                                                 aria-hidden="true"> {{ order.total_price }}&nbsp;元</i></p>
        <p align="center">共：{{ detail_list|length }}&nbsp;份</p>
        <div style="position: absolute;right:25%;top: 5%">
            <dl class="dl-horizontal">
                <dt>订单状态：</dt>
                <dd>{% if order.order_status == 0 %}
                    已取消
                {% elif order.order_status == 1 %}
                    未接单
                {% elif order.order_status == 2 %}
                    已接单
                {% elif order.order_status == 3 %}
                    骑手接单
                {% elif order.order_status == 3 %}
                    骑手取到商品
                {% elif order.order_status == 3 %}
                    已送达
                {% endif %}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>用户名：</dt>
                <dd>{{ address.address_name }}{% if address.sex == 1 %}
                    （先生）
                {% else %}
                    （女士）
                {% endif %}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>地址：</dt>
                <dd>{{ address.location }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>手机号：</dt>
                <dd>{{ address.address_tel }}</dd>
            </dl>
        </div>
    </div>
</div>
</body>
</html>

templates/Store/OrderManage.html
{% extends 'Store/storebase.html' %}
{% block title %}
    订单管理
{% endblock %}
{% block leftside %}
    {% include 'Store/storeleftside.html' %}
{% endblock %}
{% block css %}
{% endblock %}
{% block main %}
    <div class="main">
            <div class="input-group">
                <input type="text" class="form-control" id="search_time" placeholder="根据时间查找订单">
                <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="search_order(1)">查找</button>
                </span>
            </div>
            <div class="input-group">
                <input type="text" id="search_id" class="form-control" placeholder="查找订单编号">
                <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="search_order(2)">查找</button>
                </span>
            </div>
        <div style="width: 1200px;margin: 0 auto;padding-top: 40px;font-size: 20px">
            <table class="table table-hover ">
                <thead>
                <tr>
                    <th>订单编号</th>
                    <th>订单详情</th>
                    <th>订单价格</th>
                    <th>订单状态</th>
                    <th>创建时间</th>
                    <th>结束时间</th>
                </tr>
                </thead>
                <tbody>
                {% for order in order_list %}
                    <tr>
                        <td>{{ order.order_id }}</td>
                        <td>
                            <a data-toggle="modal" href="/store/orderdetail/{{ order.order_id }}"
                               data-target="#show_details">查看详情</a></td>
                        <td>{{ order.total_price }}</td>
                        <td>{% if order.order_status == 0 %}
                            已取消
                        {% elif order.order_status == 1 %}
                            未接单
                        {% elif order.order_status == 2 %}
                            已接单
                        {% elif order.order_status == 3 %}
                            骑手接单
                        {% elif order.order_status == 3 %}
                            骑手取到商品
                        {% elif order.order_status == 3 %}
                            已送达

                        {% endif %}</td>
                        <td>{{ order.create_date }}</td>
                        <td>{% if order.finish_time == None %}暂无{% else %}{{ order.finish_time }}{% endif %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation">
          <ul class="pagination">
              {{ page_info.pager|safe}}
          </ul>
        </nav>
    </div>
    <!-- Modal -->
    <div class="modal fade " id="show_details" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $("#leftside li:eq(2)").addClass("layui-this")
        $('#show_details').on('hidden.bs.modal', function () {
            $(this).removeData("bs.modal");
            $(this).find(".modal-content").children().remove();
        })
        layui.use('laydate', function () {
            var laydate = layui.laydate;
            //日期范围
            laydate.render({
                elem: '#search_time'
                , range: true
            });
        });
        function search_order(type) {
            if(type===1){
                {#根据时间查找#}
                var search_time=$("#search_time").val()
                var time=search_time.split(" - ")
                console.log(time)
                location.href='/store/searchorder/?type=1&starttime='+time[0]+'&endtime='+time[1]

            }else{
                var search_id=$("#search_id").val()
                location.href='/store/searchorder/?type=2&search_id='+search_id
            }

        }
    </script>
{% endblock %}

templates/Store/StoreLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/Store/UpdateStoreInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel" align="center">修改商家信息</h4>
    </div>
            <form class="form-horizontal" action="/store/updateinfo/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
    <div class="modal-body">

            <div class="form-group">
                <label class="col-sm-2 control-label">账号</label>
                <div class="col-sm-10">
                    <p class="form-control-static">{{ store.account }}</p>
                </div>
            </div>
            <div class="form-group">
                <label for="id_store_avatar" class="col-sm-2 control-label">头像</label>
                <div class="col-sm-10">
                    {{ form.store_avatar }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_store_name" class="col-sm-2 control-label">商家名称</label>
                <div class="col-sm-10">
                    {{ form.store_name }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_open_time" class="col-sm-2 control-label">开店时间</label>
                <div class="col-sm-10">
                    {{ form.open_time }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_open_time" class="col-sm-2 control-label">打烊时间</label>
                <div class="col-sm-10">
                    {{ form.close_time }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_store_tel" class="col-sm-2 control-label">联系方式</label>
                <div class="col-sm-10">
                    {{ form.store_tel }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_address" class="col-sm-2 control-label">地址</label>
                <div class="col-sm-10">
                    {{ form.address }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_remark" class="col-sm-2 control-label">商家介绍</label>
                <div class="col-sm-10">
                    {{ form.remark }}
                </div>
            </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="submit" class="btn btn-primary">保存</button>
      </div>
    </form>
</div>
</body>
</html>

templates/Store/addGoodType.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel" align="center">商品类型</h4>
                <div class="input-group">
                    <input type="text" name="type_name" class="form-control" placeholder="添加商品类型名">
                    <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="addgoodtype()">添加</button>
                    </span>
                </div>
    </div>
    <div class="modal-body">
        <table class="table table-hover">
        <thead>
        <tr>
            <td>名称</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody id="typebody">
        {% for type in type_list %}
            <tr>
            <td>{{ type.goodtype_name }}</td>
            <td><a onclick="deltype(this,{{ type.goodtype_id }})">删除</a></td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
</div>
<script>
    function addgoodtype(){
        var type_name=$("input[name='type_name']").val()
        if(type_name){
            $.ajax({
            url: "/store/addgoodtype/",
            method: "post",
            dataType: "JSON",
            data: {"type_name":type_name,"csrfmiddlewaretoken": '{{ csrf_token }}'},
            traditional: true,
            success: function (args) {
                if (args.status) {
                    $("#typebody").append("<tr><td>"+type_name+"</td><td><a onclick='deltype(this,"+args.goodtype_id+")'>删除</a></td></tr>")
                } else {
                    alert(args.message)
                }
            }
        })
        }
    }
        function deltype(obj,id){
            $.ajax({
            url: "/store/delgoodtype/",
            method: "post",
            dataType: "JSON",
            data: {"goodtype_id":id,"csrfmiddlewaretoken": '{{ csrf_token }}'},
            traditional: true,
            success: function (args) {
                if (args.status) {
                    $(obj).parent().parent().remove()
                } else {
                    alert(args.message)
                }
            }
        })

    }
</script>
</body>
</html>

templates/Store/addGoods.html
{% extends 'Store/storebase.html' %}
{% block title %}添加商品{% endblock %}
{% block leftside %}
    {% include "Store/storeleftside.html" %}
{% endblock %}
{% block main %}
    <div class="main" style="background-color: #efefef">
    <ol class="breadcrumb">
        <li><a href="#">商品管理</a></li>
        <li class="active">添加商品</li>
    </ol>
<form action="/store/addgood/" method="post" enctype="multipart/form-data" style="width: 1000px;margin: 0 auto">
    {% csrf_token %}
  <div class="form-group">
    <label for="id_good_pic">商品图片</label>
    {{form.good_pic}}
  </div>
      <div class="form-group">
    <label for="id_good_name">类型</label><br>
      {{ form.good_type}}
          <a style="display: inline" href="/store/addgoodtype" data-toggle="modal" data-target="#goodtypeModal">没有你想要的？go添加</a>
  </div>
  <div class="form-group">
    <label for="id_good_name">名称</label>
      {{ form.good_name}}
      <p class="help-block" style="color: red">{{ form.errors.good_name.0 }}</p>
  </div>
  <div class="form-group">
    <label for="id_price">价格(元/份)</label>
      {{ form.price}}
    <p class="help-block" style="color: red">{{ form.errors.price.0 }}</p>
  </div>
  <div class="form-group">
    <label for="id_discount">优惠</label>
      {{ form.discount}}
    <p class="help-block" style="color: red">{{ form.errors.discount.0 }}</p>
  </div>
      <div class="form-group">
    <label for="id_good_num">库存</label>
      {{ form.good_num}}
    <p class="help-block" style="color: red">{{ form.errors.good_num.0 }}</p>
  </div>
    <div class="form-group">
    <label for="id_good_num">备注</label>
      {{ form.remark}}
    <p class="help-block" style="color: red">{{ form.errors.remark.0 }}</p>
  </div>
    <input type="submit"  value="添加" class="btn btn-primary">
</form>
        </div>
        <!-- Modal -->
    <div class="modal fade " id="goodtypeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script>
$("#leftside li:eq(1)").addClass("layui-nav-itemed")
$("#addgood").addClass("layui-this")
$('#goodtypeModal').on('hidden.bs.modal', function (e) {
    location.reload()
})
</script>
{% endblock %}

templates/Store/echartDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {{ echart|safe }}
    </div>
</div>
</body>
</html>

templates/Store/goodTypeManage.html
{% extends 'Store/storebase.html' %}
{% block title %}添加商品
{% endblock %}
{% block leftside %}
    {% include "Store/storeleftside.html" %}
{% endblock %}
{% block main %}
    <div class="main">
    <ol class="breadcrumb">
        <li><a href="#">商品管理</a></li>
        <li class="active">商品类型</li>
    </ol>
    {% for goodtype in goodtype_list %}

        {{ goodtype }}
    {% endfor %}
    </div>
{% endblock %}

{% block script %}
<script>
$("#leftside li:eq(1)").addClass("layui-nav-itemed")
$("#goodtype").addClass("layui-this")
</script>
{% endblock %}

templates/Store/updateGood.html
{% extends 'Store/storebase.html' %}
{% block title %}商品查询
{% endblock %}
{% block leftside %}
    {% include 'Store/storeleftside.html' %}
{% endblock %}
{% block main %}
    <div class="main" style="background-color: #efefef">
    <ol class="breadcrumb">
        <li><a href="/store/goodsmanage">商品管理</a></li>
        <li><a href="/store/goodsmanage">商品查询</a></li>
        <li class="active">商品修改</li>
    </ol>

<form action="/store/updategood/{{ good_id }}" method="post" enctype="multipart/form-data" style="width: 1000px;margin: 0 auto">
    {% csrf_token %}
  <div class="form-group">
    <label for="id_good_pic">商品图片</label>
    {{form.good_pic}}
  </div>
      <div class="form-group">
    <label for="id_good_name">类型</label>
      {{ form.good_type}}
  </div>
  <div class="form-group">
    <label for="id_good_name">名称</label>
      {{ form.good_name}}
      <p class="help-block" style="color: red">{{ form.errors.good_name.0 }}</p>
  </div>
  <div class="form-group">
    <label for="id_price">价格(元/份)</label>
      {{ form.price}}
    <p class="help-block" style="color: red">{{ form.errors.price.0 }}</p>
  </div>
  <div class="form-group">
    <label for="id_discount">优惠</label>
      {{ form.discount}}
    <p class="help-block" style="color: red">{{ form.errors.discount.0 }}</p>
  </div>
      <div class="form-group">
    <label for="id_good_num">库存</label>
      {{ form.good_num}}
    <p class="help-block" style="color: red">{{ form.errors.good_num.0 }}</p>
  </div>
    <div class="form-group">
    <label for="id_good_num">备注</label>
      {{ form.remark}}
    <p class="help-block" style="color: red">{{ form.errors.remark.0 }}</p>
  </div>
    <input type="submit"  value="修改" class="btn btn-primary">
</form>
    </div>
{% endblock %}
{% block script %}
<script>
$("#leftside li:eq(1)").addClass("layui-nav-itemed")
$("#goodsmanage").addClass("layui-this")
</script>
{% endblock %}